sudo: required
dist: trusty

language: haxe

haxe:
  - "4.1.1"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - npm run lix install gh:skial/min-max

script:
  - npm run lix use haxe $TRAVIS_HAXE_VERSION
  - npm run haxe build.hxml


deploy:
  - provider: script
    haxe: 4.1.1
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true