sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.7"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - npm lix use haxe $TRAVIS_HAXE_VERSION
  - npm run haxe build.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true